- bblfsh/client.py
- Fixes what we can fix of bblfsh/python-driver/issues/55.
- Some PEP8 formatting.
> Moved imports to functions to avoid prematurely triggering rGPC hangs after forks

- Makefile
- setup.py
Last version before the upgrade to sdkv1. CI will probably fail (because it'll retrieve the Python driver 0.9.0).
> Bump libuast to v0.2.1

- bblfsh/client.py
- bblfsh/test.py
Fixes bblfsh/java-driver/issues/49.
> Read the file as byte stream as the go client and drivers natively do

- .travis.yml
- Makefile
- bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/generated_pb2.py
- bblfsh/gopkg/in/bblfsh/sdk/v1/protocol/generated_pb2_grpc.py
- gopkg.in/bblfsh/sdk.v1/protocol/generated.proto
- setup.py
- Updates the `.proto` files to the latest versions in the SDK refactor and regenerates the `.pb2` files.
- Bump version to 2.0.0.
Doesn't include yet the request to download the pb2 files from a release zip on pip install, this will come in a later PR.
> Updated protofiles from the SDK refactor. Bump version

- bblfsh/pyuast.c
- bblfsh/test.py
- setup.py
From #29.
Changes `filter()` to return an iterator object instead of a list. This goes in line with what most Python 3.x APIs do. It also breaks any code doing a `len(result)` or `result[index]` which would have to be changed to `len(list(result))`, `list(result)[0]` or `any(result)` to check if there is any element. 
This was agreed as a good thing on the linked issue but I think we should get feedback from other Python client users before merging.
> [RFC] Feature/iterator result

- README.md
Signed-off-by: Alfredo Beaumont <alfredo.beaumont@gmail.com>
> docs: Add a link to guide.

- README.md
- bblfsh/fixtures/issue60.py
- bblfsh/launcher.py
- bblfsh/test.py
- setup.py
Fixes #60 (was really fixed on libuast). 
- Test and fixture for issue 60.
- Update libuast dependency to 1.5.0, compile with C++11 standard.
- Tests: Use bblfshd + driver install instead of the server.
- Update `README.md`.
Note: CI will fail until bblfsh/libuast/pull/54 is merged. After that merge I'll update the libuast dependency version.
> Test for issue 60 + bblfshd/libuast update

- README.md
Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>
> Fix capitalizing bug in the README example

- bblfsh/pyuast.c
- bblfsh/test.py
- setup.py
(Branched from amlweems:fix-memory-leak)
- Apply the memory leaks [detected and fixed by @amlweems](https://github.com/bblfsh/client-python/pull/74) with an aditional one for the `String` helper functions that allows the fix for `ItemAt` to work.
- Test (also from @amlweems branch) to check that memory doesn't increase after 100 `filter()` calls. 
> Fix memory leaks (thanks @amlweems)

- README.md
Adding to dependency section of README as `pip install` depends on it:
- `curl` i.e https://github.com/bblfsh/client-python/blob/0037d762563ab49b3daac8a7577f7103a5628fc6/setup.py#L72
- `g++` https://github.com/bblfsh/client-python/blob/0037d762563ab49b3daac8a7577f7103a5628fc6/setup.py#L17
Otherwise `pip install bblfsh` fails on a system, if those native packages not present.
> Doc: update README, add required native dependency

- bblfsh/memtracker.cc
- bblfsh/memtracker.h
- bblfsh/pyuast.cc
- bblfsh/test.py
- setup.py
Fixes #92.
- Fixed several memleaks. All runaway memleaks seem to be fixed, tested with a 200.000 iterations run.
- Removed redundant method in memtracker (and calls to it).
- Other small improvements.
> Memleaks and other fixes

- bblfsh/pyuast.cc
- bblfsh/test.py
- setup.py
Fixes #100.
- Fix calls in the "HasXXX" position functions to `AttributeValue` without decreasing the reference of the returned object or adding it to the memory tracker which were leaking in a specific case
- Added ugly warnings about the need to do that on `Attribute` and `AttributeValue`.
- Added two new tests for memleaks covering the bug.
- Updated the build to the latest libuast and changed URL.
> Fix leaks in HasPosition calls

- bblfsh/pyuast.cc
- setup.py
Small change for yesterday PR to ensure not calling `Py_DECREF` on a NULL pointer.
> HasAttribute: Ensure no py_decref is called on a null pointer

- .travis.yml
> Use cwd as HOME to avoid permission errors on CI

- setup.py
Fixed version of grpcio is causing error when an application needs to use
newer compatible grpcio:
bblfsh 2.11.2 has requirement grpcio==1.13.0, but you'll have grpcio 1.17.0
which is incompatible.
In my case I stumbled on this bug that is fixed in newer grpcio:
https://github.com/grpc/grpc/issues/14088
Signed-off-by: Maxim Sukharev <max@smacker.ru>
> Use version range for grpcio instead of exact version

- bblfsh/client.py
The `raw` parameter was removed from `parse` in bd8c2d57, but we forgot to drop
the doc string for it.
Fixes #143.
Signed-off-by: M. J. Fromberger <michael.j.fromberger@gmail.com>
> Remove an obsolete docstring annotation.

- setup.py
Some of our code uses type annotations on variable declarations, which were introduced by [PEP 526](https://www.python.org/dev/peps/pep-0526/) with Python 3.6. There does not seem to be any good reason not to prefer newer versions of Python 3, since we are already incompatible with Python 2, so this change drops the 3.4 and 3.5 tags from the PyPI configuration.
Fixes #153.
> Require Python ≥ 3.6.

- setup.py
This is a follow-up to #154. Recent versions of setuptools allow specifying [explicit version constraints][1] for Python. Older versions will ignore it, but it can't hurt.
[1]: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
> Include a python_requires clause in the setup file.

- setup.py
Part of the fix for https://github.com/bblfsh/client-python/issues/156.
Part of the `pyuast` build process fetches a binary release of `libuast`. Previously, the release version was pinned to `linux-amd64`, and therefore did not link correctly on macOS (Darwin).
This change makes the build script consult `sys.platform`. The default remains `linux-amd64` in case someone has another platform; if it was wrong before it will still be wrong, but in the same way.
> Derive the libuast os/arch selector from sys.platform.

- bblfsh/pyuast.cc
* ~~Deletes unbalanced `Py_INCREF` [here](https://github.com/bblfsh/python-client/blob/dfda83d6d29e4a385690deda450c6f077ee1e84c/bblfsh/pyuast.cc#L347), and analogously for `PythonContext_filter`. The rationale behind this is that this `Py_INCREF` has no effect because of `NodeIterator` [saving a pointer to `ctx`](https://github.com/bblfsh/python-client/blob/dfda83d6d29e4a385690deda450c6f077ee1e84c/bblfsh/node_iterator.py#L19). Another alternative would be to do a `Py_DECREF` in `PyUastIterExt_dealloc`, but `PyUastIterExt` is also used for free contexts which are not associated to a Python object, so I think this is the cleanest solution.~~ This would be addressed separately #181,
* Python shares ints and strings in memory (for ints I think it is in a certain range [0,256]). Let us suppose …
> Fixes Python object caching memory leaks

- bblfsh/test.py
- bblfsh/tree_order.py
- setup.py
It needs a new release of  [sdk](https://github.com/bblfsh/sdk) and [libuast](https://github.com/bblfsh/libuast) to work (travis would fail until we do them). It also includes d86fefe which should have been included in #180 :see_no_evil: and adds the order for positions as is in the SDK, instead of lexicographical order of `(offset, line, column)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/python-client/187)
> Adds children order

- bblfsh/client.py
Mirrors https://github.com/bblfsh/scala-client/pull/133. We already had a `timeout` parameter here, but with default value of `None` (no timeout). Default timeout has been set to 60 seconds as in `scala-client`
Signed-off-by: ncordon <nacho.cordon.castillo@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/python-client/194)
> Adds timeout of 60 seconds to parse requests
