bblfsh/launcher.py
Please move the tag after merge!
=> Check the container's status in ensure_bblfsh_is_running()

README.md, bblfsh/__main__.py, bblfsh/client.py, bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2.py, bblfsh/github/com/bblfsh/sdk/protocol/generated_pb2_grpc.py, bblfsh/github/com/bblfsh/sdk/uast/generated_pb2.py, bblfsh/test.py, github.com/bblfsh/sdk/protocol/generated.proto, github.com/bblfsh/sdk/uast/generated.proto
Travis build will fail until we merge the SDK PR.
=> renamed SD api calls and parse_uast (to parse) module function

bblfsh/launcher.py
Before: if the container was found and not running - do nothing.
After: attempt to start it
=> Start the existing containers which are not running

gopkg.in/bblfsh/sdk.v0/protocol/generated.proto, gopkg.in/bblfsh/sdk.v0/uast/generated.proto, setup.py
Seems like I forgot to `git mv` them in the last PR.
Edit: CI it's crashing with a SIGSEGV when calling libuast's `filter`, it's also crashing with the `~master` version (which previously worked) so it must be related to some dependency; I'm investigating the problem.
=> move proto files

setup.py
=> Bump version to 2.1.0 for pypy upload.

bblfsh/client.py, bblfsh/test.py, setup.py
=> Added "native_parse" and "version" requests.

setup.py
=> Added grpcio-tools dependency to setup.py, remove unneeded code

bblfsh/pyuast.c, bblfsh/test.py, setup.py
Signed-off-by: Alfredo Beaumont <alfredo.beaumont@gmail.com>
=> libuast: Bump to 1.4.1 and improve error handling

setup.py
=> Upgrade to SDK 1.8.0 to get the Language field in Responses.

bblfsh/client.py, bblfsh/test.py
=> Check for non UTF8 contents + test. Factorize content loading.

setup.py
=> Version 2.8.0

requirements.txt, setup.py
Resolves https://github.com/bblfsh/client-python/issues/68
=> Add protobuf into dependencies

README.md, bblfsh/__init__.py, bblfsh/pyuast.c, bblfsh/test.py, setup.py
=> Added libuast typed filter functions. Other fixes & factorizations.

setup.py
=> Fixed grpcio version to 1.9.1 because of problems with 1.10.0

bblfsh/memtracker.cc, bblfsh/memtracker.h, bblfsh/pyuast.cc, bblfsh/test.py, setup.py
Memory tracker to make easier and less bug-prone to track allocations inside Node's interface functions.
Fixes #82
=> New memory tracker

bblfsh/memtracker.cc, setup.py
=> Bump version

MANIFEST.in, setup.py
=> Add missing file to MANIFEST

bblfsh/__init__.py, bblfsh/test.py, setup.py
=> Binding for position iterator + tests + update to grpcio 1.10.0

bblfsh/test.py, setup.py
Requires: bblfsh/libuast/pull/79
=> Change position iterator unittest to match the expected ordering of the fixed libuast

requirements.txt, setup.py
=> Use the same grpcio version dependency on setup.py and requirements

.travis.yml, setup.py
- Replace calls to coreutils with equivalent Python APIs
- os.path.join
=> Rework setup.py to be portable

bblfsh/aliases.py, bblfsh/client.py, bblfsh/test.py, setup.py
Fixes #98. Also updates an unittest to make it compatible with v1 and v2 branches and add the recently released Python 3.7 to the CI.
cc @zurk
=> Add the SupportedLanguages protocol call

bblfsh/pyuast.cc, setup.py
=> Remove compound literals since MSVC doesnt support them

.travis.yml, setup.py
=> Fix import failure on Python 3.7

setup.py
=> Bump version again

README.md
Add a missing closing parenthesis
=> README.md: fix a typo in the example snippet

.travis.yml, setup.py
=> Add upload to pypi from travis tags

bblfsh/__init__.py, bblfsh/__main__.py, bblfsh/client.py, bblfsh/launcher.py
Signed-off-by: Waren Long <waren@sourced.tech>
=> Add type hints

MAINTAINERS
=> Switch maintainers for the client-python repository.

.travis.yml, setup.py
Fix pypi upload from Travis.
(Note: I already uploaded manually for 3.0.0).
=> Fix pypi upload from Travis

README.md
Signed-off-by: prashik-s <prashiksahare110044@gmail.com>
=> Added missing brace in example code

bblfsh/__init__.py, bblfsh/node.py, bblfsh/roles.py, bblfsh/test_compat.py
Hey, LA team 👋 
ML team found some time to check out new client (v3) you provide for us. Here a PR to make everything work as it was. https://github.com/src-d/ml-core/pull/31 is the PR in `ml-core` that is waiting for a new release of bblfsh client. 
It is more or less obvious what I changed and why, but ask me while reviewing if it is unclear. Every change is necessary or some test fails in ml-core`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/python-client/172)
=> Fix classes for backward compatibility
